version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: yarn install --non-interactive
      - run: npx semantic-release
workflows:
  test_my_app:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
